apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec: 
      containers:
        - name: ai-app
          image: test_agent:v1
          ports:
            - containerPort: 8000

